<!DOCTYPE html>

<head>
    <title>Try and Catch</title>
    <meta charset="UTF-8">
</head>
<body>

    <h2>Try and Catch</h2>

    <script type="text/javascript">

        var arrayExe = new Array()

        arrayExe[1] = Array()
        arrayExe[1]["Name"] = "Dark"
        arrayExe[1]["Type"] = "Series"

        try {
            console.log(arrayExe[0]["Name"])
        } catch(e){
            console.log("This is the error")
            throw new Error("We are working in the problem")            
        } finally {
            console.log("It allways will pass throught here")
        } 


        /*
        If we use throw in the script it will stop at that moment, but if we just let the script with catch
        the flow will pass throught that block (Catch) and then it will keep running, it will not stop
        */
        console.log("End")

    </script>

</body>